mod browser;
mod db;
mod docker;
mod general;
mod git;
mod go;
mod homebrew;
mod ide;
mod java;
mod logs;
mod nodejs;
mod python;
mod rust_cargo;
mod shell;
mod xcode;

pub use browser::check_browser_caches;
pub use db::check_db_caches;
pub use docker::check_docker;
pub use general::{check_general_caches, check_node_modules, check_trash};
pub use git::check_git_repos;
pub use go::check_go;
pub use homebrew::check_homebrew;
pub use ide::check_ide_caches;
pub use java::check_gradle_maven;
pub use logs::check_system_logs;
pub use nodejs::check_npm_yarn;
pub use python::check_python;
pub use rust_cargo::check_rust;
pub use shell::check_shell_caches;
pub use xcode::check_xcode;
